

config: |-
  broker.id=-1
  num.network.threads=2
  num.io.threads=8
  socket.send.buffer.bytes=1048576
  socket.receive.buffer.bytes=1048576
  socket.request.max.bytes=104857600
  log.dirs=/bitnami/kafka/data
  num.partitions=1
  num.recovery.threads.per.data.dir=1
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  transaction.state.log.min.isr=1
  log.retention.hours=168
  log.segment.bytes=536870912
  log.retention.check.interval.ms=60000
  group.initial.rebalance.delay.ms=0
  zookeeper.connect=zoko1-zookeeper


service:
  type: ClusterIP
  port: 9092

externalAccess:
  enabled: true
  service:
    port: 19092
    type: LoadBalancer

##    loadBalancerIP: [34.102.253.216]


#image:
#  registry: harbor.skyfire.internal
#  tag: 2.4.0-debian-10-r15

persistence:
  accessMode: ReadWriteOnce
  size: "3Gi"
  ##size: "10Gi"
  ##storageClass: nfs-client

## Timeout in ms for connecting to zookeeper.
zookeeperConnectionTimeoutMs: "1000000"
deleteTopicEnable: true

replicaCount: 1
##
## Zookeeper chart configuration
##
## https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml
##
zookeeper:
  enabled: false

## This value is only used when zookeeper.enabled is set to false
##externalZookeeper:
##  servers: zoko1-zookeeper
