apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    application: greeting
    team: rainier
spec:
  containers:
  - image: paradise22/sample-app:latest
    name: sample-app
    livenessProbe:
      initialDelaySeconds: 20
      httpGet:
        path: /actuator/health
        port: 8080
    ports:
    - containerPort: 8080
      protocol: TCP
