apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: sample-app
      labels:
        application: greeting
        team: rainier
    spec:
      containers:
      - image: paradise22/sample-app:1.0
        name: sample-app
        livenessProbe:
          initialDelaySeconds: 80
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          periodSeconds: 3
          initialDelaySeconds: 60
          failureThreshold: 2
          timeoutSeconds: 2
          httpGet:
            path: /actuator/health
            port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP