{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.defaultName }}
  namespace: {{ .Release.Namespace }}
  labels:
    rsGroup: {{ .Values.resourceGroup }}
    app: {{ .Values.baseName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}